### ISSUE TITLE
Opera Mini

### ISSUE THREAD

**Issue by pakpenyo** [scottsweb/mobble#14]
Hi,

Can you add Opera Mini specific class? It's different between Opera and Opera Mini. But i don't know with opera mobile, but i think it's not Opera Mini.

Thanks a lot.

**Comment by scottsweb** [comment]
The underlying API would allow you to do this fairly easily:

```php
if ( ! is_admin() ) {
	add_filter( 'body_class', 'my_body_class' );
}

function my_body_class( $classes ) {
	global $mobble_detect;
        if ( $mobble_detect->isOpera() ) {
                $classes[] = "opera"; 
        }
        return $classes;
}
```

There is also an example of detecting Opera mini here: http://mobiledetect.net/
