### ISSUE TITLE
Screen size for is_mobile/is_smartphone

### ISSUE THREAD

**Issue by Beee4life** [scottsweb/mobble#15]
Hi, loving your plugin.

I have a question because I encountered some unexpected behaviour. 

I used is_mobile/is_smartphone and when I used the Chrome responsive view, the content was hidden immediately.

I expected it to be hidden on a smaller screen size. Can u enlighten me a bit more ?

**Comment by scottsweb** [comment]
Hi. It is not based on screen size at all. The PHP detects the user agent, so if the Chrome developer tools are emulating a mobile user agent it should work as expected.

**Comment by Beee4life** [comment]
Thanks.
