### ISSUE TITLE
Trying to hide Primary Menu Nav bar for mobile

### ISSUE THREAD

**Issue by BlueCoralSwim** [scottsweb/mobble#17]
I've been unsuccessful putting in CSS to disable it.  I think the child/parent theme is just over riding it.  I keep beating my head on this, so any suggestions out there?  

Mind you I do not have a mobile navigation menu selected.  Only the primary menu as primary.

Here's the header php:

<?php
/**
 * Header Template
 *
 * Here we setup all logic and XHTML that is required for the header section of all screens.
 *
 * @package WooFramework
 * @subpackage Template
 */
?><!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Blue Coral Swimwear | Designer Women's Swimsuits and Bikinis</title>
<meta name="description" content="Blue Coral Swimwear lets women feel sexy and confident, glamorous, flirty, and fun all all with a body positive feeling." />
<meta name="keywords" content="" />
<meta name="robots" content="INDEX,FOLLOW" />

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>
  
  
<script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '534382196734733');
  fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=534382196734733&ev=PageView&noscript=1"
/></noscript>

  function hide_pop() {
  	document.getElementById('def_pop').style.display="none";
  }
  
 //$(window).load(function() {
    //var result = document.getElementById('header').offsetHeight;
    //alert(result);
  //});
  
  $(function(){
    /*
   $(window).scroll(function(){
       var result = document.getElementById('header').offsetHeight;
       var scrolltop=$(window).scrollTop();
       if($(window).scrollTop()>=result){
           $("#navigation").addClass( "fixed_nav" );
           $('.menus').attr('id', 'wrapper');
       }
       else {
           $("#navigation").removeClass( "fixed_nav" );
           $('.menus').removeAttr('id');
       }
   });
*/
    
});
  
 
$( document ).ready(function() {
    $("#navigation").addClass( "fixed_nav" );
}); 
</script>
<?php wp_head(); ?>
<?php woo_head(); ?>
</head>
<body <?php body_class(); ?>>
  
 <script>
  fbq('track', 'Purchase');
</script>
<script>
  fbq('track', 'Lead');
</script>
<script>
  fbq('track', 'AddToCart');
</script>
<script>
  fbq('track', 'InitiateCheckout');
</script>

<?php woo_top(); ?>
<div class="heading-images">
<a title="Inspired by your beauty" href="<?php echo home_url(); ?>">
<img src="wp-content/uploads/2016/11/Blue-Coral-PMS-308C.small_.web_.png" img width="210" height="52" alt="Inspired by your beauty" class="header-image"  "middle"/>
</a>

</div>
<div id="wrapper">

	<div id="inner-wrapper">

	<?php woo_header_before(); ?>

	<header id="header" class="col-full">

		<?php woo_header_inside(); ?>

	</header>
	<?php woo_header_after(); ?>

If need be here's the Top Nav/ Header/Primary Nav code in the functions php file:

// Top Navigation
		$options['woo_top_nav_font'] = array( 'size' => '1.5', 'unit' => 'em', 'face' => $open_sans, 'style' => 'normal', 'color' => '#999' );

		// Header
		$options['woo_font_logo'] = array( 'size' => '1.5', 'unit' => 'em', 'face' => $roboto, 'style' => '300', 'color' => '#000000' );
		$options['woo_font_desc'] = array( 'size' => '1.5', 'unit' => 'em', 'face' => $open_sans, 'style' => 'normal', 'color' => '#999999' );

		// Primary Navigation
		$options['woo_nav_font'] = array( 'size' => '2.5', 'unit' => 'em', 'face' => $open_sans, 'style' => 'normal', 'color' => '#ffffff' );
		$options['woo_nav_bg'] = '#6ec095';
		$options['woo_nav_hover_bg'] = '#4C5567';

**Comment by scottsweb** [comment]
I cannot read this code very well (you can format it better using the formatting tools above the comment box) and you do not appear to be using any functions from this plugin. I think you may have posted this to the wrong place. Closing.
