### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by Shipwreck** [scottsweb/mobble#4]
This is the most interesting method I've seen for responsive thumbnails. Are the techniques still current and any plans to continue with the WordPress plugin?

**Comment by scottsweb** [comment]
> If you did update mobble it would be good to rename the Mobile_Detect.php class. Currently you use mobile-detect.php. Was there a reason for this? 

Not a good reason. I have changed this today to make it easier going forwards. 

> Regarding caching. I recently moved over to WP Engine for hosting and was concerned that their server caching would essentially break mobble. To my surprise – and delight – it didn't! 

This is very interesting. I always just assumed that it would not work. This suggests that the WP Engine cache is smart enough to be device aware. Thanks for letting me know, I would love to know how they have this setup.
