### ISSUE TITLE
Feature Request: Secondary Option To Use Browscap

### ISSUE THREAD

**Issue by jaswsinc** [scottsweb/mobble#6]
Love your work on this! Thank you.

It would be great if there was a secondary option
to use Browscap with this plugin. http://browscap.org/

**Comment by scottsweb** [comment]
Would love to know more about why you feel browscap would be a better solution to the problem of browser detection. What does it give us that mobile detect doesn't?

From the looks of things the browscap file is ~15MB .ini file which is fairly substantial. I am also not familiar with this file-type. Is it something that can safely be deployed across standard/shared hosting setups?
