### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by rpkoller** [scottsweb/mobble#7]
Hi are you interested in getting your plugin translated into german? Wouldn't be that many strings to translate. I could quickly set it up and place a pull request. Only a few questions upfront. How should the mo and po file folder be called? lang or languages? And which textdomain would you wanna use? `mobble`? Cheers r.

**Comment by scottsweb** [comment]
Sounds good to me! thanks for offering. Use a folder called `languages` and a text domain of `mobble`. I will take care of the rest.

Thanks again!

**Comment by rpkoller** [comment]
I am already done. I just struggle with two sentences and how to translate them into german. Rather difficult to finde appropriate translations for the one with mobify the body class and the liner note with the flattered flattr. ;) especially the last one is a tough nut ;)

**Comment by scottsweb** [comment]
Some strings that might be easier to translate:

* If you find this plugin useful I'd be flattered to be Flattr'd 
* Support this plugin with Flattr

and

* Mobify body class?
* Add mobble classes to the body?

Would that make it easier for you to translate? or are you happy with the ones in your pull request. Let me know and I can get it merged.

Thanks for this :+1:

**Comment by rpkoller** [comment]
Hi Scott. The strings in the pull request are already translated freely. The first one roughly says something like " If you find this plugin useful i would be grateful if you flatter it". The second one says "Set the mobble body classes?". I've only worried in the first place when i tried to exactly replicate the puns. But as you can see in the end i've minded only the meaning. So i think the pull request should be fine and no further changes should be necessary. Cheers r.

**Comment by scottsweb** [comment]
Perfect. Thank you!
